# Generated by Django 3.0.8 on 2020-07-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200717_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('Can mark returned', 'Set book as returned'),)},
        ),
    ]
